version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
