name: Build and deploy Python app to Azure Web App - FlightSpark

on:
  push:
    branches:
      - deploy1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd server
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd server
          pip install -r requirements.txt

      # Optional: Add step to run tests here
      # - name: Run tests
      #   run: |
      #     cd server
      #     pytest

      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip . -x "*.git*" "*.venv*" "*.pytest_cache*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip -d server

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'FlightSpark'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1ad21525180d4503aa85b879cf7e0eaf }}
